battery_capacity: 10000
battery_discharge_rate: 100
camera_fov: 60
camera_height: 0.3
gripper_capacity: 5.0
gripper_open_close_time: 1.0
height: 0.4
length: 0.7
max_acceleration: 0.5
max_speed: 1.5
sensor_range: 5.0
width: 0.5
